Pass [u8] instead of [u32] for push constants
gfx-rs/wgpu-rs pull request #549
Opened 2020-09-03 04:03 UTC by PENGUINLIONG

2020-09-03 04:33 UTC, cwfitzgerald requested changes

2020-09-03 04:33 UTC, cwfitzgerald commented on src/backend/direct.rs
> +                    data.as_ptr() as *const u32,
This api should be changed in wgpu-core to take a pointer to u8. As of right now this is unsound as the data may not be aligned to 4 bytes, causing ub on dereference.

2020-09-15 13:33 UTC, kvark commented
@PENGUINLIONG why closing?

2020-09-15 13:39 UTC, PENGUINLIONG commented
> @PENGUINLIONG why closing?

😥 wow i didn't actually. probably an accident

2020-09-15 16:40 UTC, PENGUINLIONG commented
I'm reopening this. It would fail the checks for now but it should work with the upgraded `wgpu`.

2020-10-21 15:03 UTC, cwfitzgerald commented
Could you rebase/update this?

2020-10-21 21:53 UTC, PENGUINLIONG commented
Should be good to go :)

2020-10-21 22:20 UTC, cwfitzgerald approved these changes
Could you squash this, then we're good to go.

2020-10-25 16:54 UTC, PENGUINLIONG commented
Oh, I just realized @kvark has already updated the push constant interfaces. Closing this.

2020-10-25 16:54 UTC, closed without merging